### ISSUE TITLE
updated contact info?

### ISSUE THREAD

**Issue by wimdecorte** [nedbsolutions/fmEZCharts#1]
A client of mine has been trying to contact you by email for support on your purchased product but all emails bounce.
Please reply here and we can take it from there.

**Comment by nedbsolutions** [comment]
Hello Wim,

We had a couple week period where there was an issue when we switched email providers. I has since been resolved. Please try contacting support@fmezcharts.com and if you receive a bounce, I also sent you a request to connect on LinkedIn.

**Comment by wimdecorte** [comment]
Thanks.
