### ISSUE TITLE
Charts not working in FM 19.3

### ISSUE THREAD

**Issue by Astariz** [nedbsolutions/fmEZCharts#2]
Charts worked fine in 19.2, updated to 19.3 and now in place of the chart is the javascript code. 19.3 updated webviewer from IE11 to Microsoft Edge (Chromium).

**Comment by nedbsolutions** [comment]
We are aware of this issue and working on a fix for it. I will update here when it is complete.

**Comment by nedbsolutions** [comment]
@Astariz - Replace data: text/html, with data:text/html, 

The space is incorrect and causes the break in 19.3.2

**Comment by nedbsolutions** [comment]
Will be applying a fix to the repo shortly.

**Comment by Astariz** [comment]
Any updates to this? The fmEZCharts sample file is currently unusable on anything newer than 19.2.

**Comment by nedbsolutions** [comment]
Resolved. The file has been updated in the repo. Any chart code that was created in the previous version needs to have the following change applied. Replace data: text/html, with data:text/html,
